-- rename table
alter table THUMBNAIL_COLLECTION
    RENAME TO _THUMBNAIL_COLLECTION_OLD;
alter table THUMBNAIL_READLIST
    RENAME TO _THUMBNAIL_READLIST_OLD;

-- remade table with new format
CREATE TABLE THUMBNAIL_COLLECTION
(
    ID                 varchar  NOT NULL PRIMARY KEY,
    SELECTED           boolean  NOT NULL DEFAULT 0,
    THUMBNAIL          blob     NULL,
    URL                varchar  NULL,
    TYPE               varchar  NOT NULL,
    COLLECTION_ID      varchar  NOT NULL,
    CREATED_DATE       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION (ID)
);

CREATE TABLE THUMBNAIL_READLIST
(
    ID                 varchar  NOT NULL PRIMARY KEY,
    SELECTED           boolean  NOT NULL DEFAULT 0,
    THUMBNAIL          blob     NULL,
    URL                varchar  NULL,
    TYPE               varchar  NOT NULL,
    READLIST_ID        varchar  NOT NULL,
    CREATED_DATE       datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (READLIST_ID) REFERENCES READLIST (ID)
);

-- insert migrated data
-- make URL to null for now
INSERT INTO THUMBNAIL_COLLECTION (ID, SELECTED, THUMBNAIL, URL, TYPE, COLLECTION_ID, CREATED_DATE, LAST_MODIFIED_DATE)
SELECT ID, SELECTED, THUMBNAIL, NULL, TYPE, COLLECTION_ID, CREATED_DATE, LAST_MODIFIED_DATE
FROM _THUMBNAIL_COLLECTION_OLD;

INSERT INTO THUMBNAIL_READLIST (ID, SELECTED, THUMBNAIL, URL, TYPE, READLIST_ID, CREATED_DATE, LAST_MODIFIED_DATE)
SELECT ID, SELECTED, THUMBNAIL, NULL, TYPE, READLIST_ID, CREATED_DATE, LAST_MODIFIED_DATE
FROM _THUMBNAIL_READLIST_OLD;

DROP TABLE _THUMBNAIL_COLLECTION_OLD;
DROP TABLE _THUMBNAIL_READLIST_OLD;
